---
- name: Deploy and start Apache HTTPD service
  hosts: alejandro
  become: true
  vars:
    web_pkg: apache2
    firewall_pkg: firewalld
    web_service: apache2
    firewall_service: firewalld
    python_pkg: python3-pymysql
    rule: http

  tasks:
    - name: Required packages are installed and up to date
      apt:
        name:
          - "{{ web_pkg  }}"
          - "{{ firewall_pkg }}"
          - "{{ python_pkg }}"
        state: latest

    - name: The {{ firewall_service }} service is started and enabled
      service:
        name: "{{ firewall_service }}"
        enabled: true
        state: started

    - name: The {{ web_service }} service is started and enabled
      service:
        name: "{{ web_service }}"
        enabled: true
        state: started

    - name: Web content is in place
      copy:
        content: "Example web content"
        dest: /var/www/html/index.html

    - name: The firewall port for {{ rule }} is open
      firewalld:
        service: "{{ rule }}"
        permanent: true
        immediate: true
        state: enabled

- name: Verify the Apache service
  hosts : localhost
  become: false
  tasks:
    - name: Ensure the webserver is reachable
      uri:
        url: http://127.0.0.1
        status_code: 200