---
- name: Enable intranet services
  hosts: servera
  become: yes
  tasks:
    - name: latest version of apache2 and firewalld installed
      yum:
        name:
          - apache2
          - firewalld
        state: latest

    - name: test html page is installed
      copy:
        content: "Bienvenidos al curso de ansible!\n"
        dest: /var/www/html/index.html

    - name: firewalld enabled and running
      service:
        name: firewalld
        enabled: true
        state: started

    - name: firewalld permits access to apache2 service
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: apache2 enabled and running
      service:
        name: apache2
        enabled: true
        state: started

- name: Test intranet web server
  hosts: localhost
  become: no
  tasks:
    - name: connect to intranet web server
      uri:
        url: http://servera.lab.example.com
        return_content: yes
        status_code: 200